projects:
  C236:
    "扫描配置":
      "Dtm": [ "defect", "xls", "问题单号" ]
      "Zentao": [ "长安智能座舱", "xlsx", "Bug编号" ]
    "测试类别":
      "系统测试": [ '陈高龙', '何仁银', '曹维', '吕淇', '黄春艳', '冯若敏', '蒋金孟', '王捷频', '谭小红', '李红霞', '蒲赛', '邓利阳', '熊礼芮', '孙澳', '张凤玲', '李杰', '杨漫', '李航', '向子怡', '付小芬', '张秦华', '张艳', '吴锡月', '王艺含' ]
      "集成测试": [ '刘曦', '潘梦雨', '周宇', '汪敏', '曾雨童', '钱凤娇', '钱凤姣' ]
      "自动化测试": [ '张巍巍', '袁锐' ]
    "公司内部类别":
      "实习生": [ '吴锡月', '王艺含', '潘梦雨' ]
      "奥莫测试": [ '何仁银', '曹维', '吕淇', '黄春艳', '冯若敏', '蒋金孟', '王捷频', '李红霞', '蒲赛', '邓利阳', '熊礼芮', '孙澳', '张凤玲', '李杰', '杨漫', '李航', '吴锡月', '王艺含', '刘曦', '潘梦雨', '周宇', '汪敏', '曾雨童', '钱凤娇', '钱凤姣' ]
      "产品技术中心测试": [ '付小芬', '向子怡', '康家加', '李杰1', '廖丹', '张艳' ]
      "外包测试": [ '张秦华', '陈高龙', '谭小红' ]
